version: "3"

services:
  web:
    container_name: app_web
    image: nginx
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - .:/usr/share/nginx/html
    environment:
      - NGINX_PORT=80
      - NGINX_HOSTNAME=api.symf.loc
      - FPM_PORT=9000
    links:
      - php-fpm
    depends_on:
      - php-fpm
    ports:
      - 80:80

  php-fpm:
    container_name: web_phpfpm74
    build: .
    volumes:
      - .:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    depends_on:
      - composer
      - db
      - redis
    ports:
      - 9000:9000

  composer:
    container_name: web_composer
    image: composer
    volumes:
      - .:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    command: "composer i"

  db:
    container_name: app_db
    image: mysql
    environment:
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=symfony
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 3306:3306

  redis:
    container_name: app_redis
    image: redis
    ports:
      - 6379:6379