routes:
  #  EXAMPLE:
  #
  #  route_name:
  #    content_type: json
  #    permission:
  #    token_need: false

  app_auth_login:
    content_type: json
    permission:
    token_need: false
  app_comment_add:
    content_type: json
    permission: 16
    token_need: true